Modify the API to serve content from AreWeHeadlessYet site
wagtail/wagtail.org pull request #150
Opened 2022-03-03 17:14 UTC by Tijani-Dia

**Context**

We want to query data from the AreWeHeadlessYet site using the API. However, we can't use the `areweheadlessyet.wagtail.org` domain for the  AreWeHeadlessYet site because it's already used for the Next.js frontend hosted in Vercel.

**Solution**

Use the `wagtail.org` domain to serve content from the AreWeHeadlessYet site - that is the goal of this PR.

2022-03-16 13:59 UTC, kaedroho commented on wagtailio/api.py
> +        areweheadlessyet_root_page = areweheadlessyet_queryset[0]
You could use ``.first()`` here which will return ``None`` if the queryset is empty so you wouldn't need to perform the query above to check if there are any pages in the queryset first:

```python
areweheadlessyet_root_page = areweheadlessyet_queryset.first()

if areweheadlessyet_root_page:
    return Page.objects.live().descendant_of(
        areweheadlessyet_root_page, inclusive=True
    )
else:
    return Page.objects.none()
```

2022-03-16 14:00 UTC, kaedroho requested changes
This looks good to me, thanks!

Just one quite minor tweak

2022-03-17 17:42 UTC, Tijani-Dia commented
Thanks, @kaedroho.

I addressed your comment.

2022-04-22 15:56 UTC, kaedroho approved these changes

2022-04-22 16:18 UTC, merged