high contrast version of logo
wagtail/wagtail.org pull request #295
Opened 2022-11-02 11:55 UTC by nicklee

High contrast version of the logo when in high contrast mode:

![Screenshot 2022-11-02 at 11 54 54](https://user-images.githubusercontent.com/298766/199483705-35f201e2-575d-446a-8d55-04aa34b7434a.png)

2022-11-02 13:44 UTC, chris-lawton approved these changes

2022-11-04 14:41 UTC, thibaudcolas requested changes
Not working with a light theme (white on white). Always go for system colors when making adjustments for forced-colors mode.

2022-11-04 14:41 UTC, thibaudcolas commented on wagtailio/static/sass/components/_footer-menu.scss
> +            fill: $color--white; // force white if in high contrast mode
```suggestion
            fill: CanvasText;
```

Just using white will work with a dark theme but not with a light theme. We need to use a system color instead.

2022-11-04 14:41 UTC, thibaudcolas commented on wagtailio/static/sass/layout/_header.scss
> +            fill: $color--white; // force white if in high contrast mode
```suggestion
            fill: CanvasText;
```

Same as above

2022-11-04 14:48 UTC, thibaudcolas approved these changes
have made the switch to `CanvasText` and make sure all system colors are allowed by linting.

2022-11-04 14:48 UTC, merged